
-- Heroes
_G.HERO_BARBARIAN = 0
_G.HERO_WARRIOR = 1
_G.HERO_ALCHEMIST = 2
_G.HERO_ARCHER = 3


_G.HeroStrings = {}

HeroStrings[ HERO_BARBARIAN ]= "HERO_BARBARIAN"
HeroStrings[ HERO_WARRIOR ]= "HERO_WARRIOR"
HeroStrings[ HERO_ALCHEMIST ]= "HERO_ALCHEMIST"
HeroStrings[ HERO_ARCHER ]= "HERO_ARCHER"
